#!/bin/bash
curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "/tmp/awscliv2.zip"
unzip "/tmp/awscliv2.zip" -d "/tmp"

if [[ "$1" == "update" ]]; then
  sudo /tmp/aws/install --bin-dir "/usr/local/bin" --install-dir "/usr/local/aws-cli" --update
else
  sudo /tmp/aws/install
fi

# Cleaning files
rm "/tmp/awscliv2.zip"
rm -rf  "/tmp/aws"