#!/bin/sh
test -z "$1" && echo "Please insert a path to search" && exit 1
query="$(echo "$*" | sed -e "s/$1 //" -e 's/\ /+/g')"
echo "https://github.com/espinosajuanma/learning/search?q=path:/$1+$query"
