#!/usr/bin/bash

declare -A codes
codes[primary]="\e[34m"   # blue
codes[secondary]="\e[35m" # magenta
codes[error]="\e[31m"     # red
codes[success]="\e[32m"   # green
codes[warning]="\e[33m"   # yellow
codes[info]="\e[36m"      # cyan
codes[light]="\e[37m"     # white
codes[normal]="\e[0m"     # reset
codes[danger]="\e[5m\e[31m" # blinking red

usage() {
  printf "log [file] [code] [message]

\e[1mCODES:\e[0m
  ${codes[primary]}primary
  ${codes[secondary]}secondary
  ${codes[error]}error
  ${codes[success]}success
  ${codes[warning]}warning
  ${codes[info]}info
  ${codes[light]}light
  ${codes[normal]}normal
  ${codes[danger]}danger\e[0m\n"
}

get_time() {
  date +'%d/%m/%Y %H:%M:%S'
}

log_message() {
  test -z "${codes[$2]}" && exit 1
  time="$(get_time)"
  printf "%b[%s] - %s\e[0m\n" "${codes[$2]}" "$time" "$3"
  echo "[$time] ${2^^} - $3" >> $1
}

main() {
  test "$1" = "help" && usage && exit
  test -z "$3" && usage && exit 1
  log_message "$1" "$2" "${*:3}"
}

main "$@"
