#!/bin/sh
#this=$(basename "$0")

echo "name: \c" && read -r name
test -z "$name" && echo "You have to set a script name!" && exit 1

echo "path ($PWD): \c" && read -r d
test -z "$d" && d="$PWD"

test -d "$d/$name" && echo "$d/$name is a directory! Can't do this." && exit 1
test -f "$d/$name" && echo "$d/$name already exist! Can't do this." && exit 1

echo "shebang (#!/bin/sh): \c" && read -r shebang
test -z "$shebang" && shebang="#!/bin/sh"

echo "$shebang" > "$d/$name" && chmod +x "$d/$name"
vim "$d/$name"
