#!/bin/bash
# note usage
#       note = show latest isosec note
#       note new = add a note in directory
#       note ls = show titles of notes in directory
#       note rm = remove last note
#       note edit = edit last note
#
#       note <isosec> edit
#       note <isosec> rm

d=$(ls -td -- */ | tail -n 1 | cut -d'/' -f1) # get last directory (isosec) in current directory

test -z "$1" && echo $d && exit 1
test $1 == "edit" && vim "$d/README.md" && exit 1
test $1 == "remove" -o $1 == "rm" && rm -rI $(note) && exit 1
test $1 == "new" -o $1 == "add" && d=$(isosec) && mkdir $d && vim "$d/README.md" && exit 1
test $1 == "list" -o $1 == "ls" && head -1 */README.md | grep '^#' | sed 's/^\# //' && exit 1
test $1 == "help" -o $1 == "h" && awk 'NR >= 2 && NR <= 10' $(readlink -f $0) | grep '^#' | sed 's/^\#//' && exit 1
if [ -d $1 ]; then
  test $2 == "edit" && vim "$1/README.md" && exit 1
  test $2 == "remove" -o $2 == "rm" && rm -rI $1 && exit 1
fi
