#!/bin/bash
uuid="$(uniq uuid)"

tmux new-window -n playground
tmux split-window -h

echo "console.log('Hello World!');" > "$HOME/playground/$uuid.js"
tmux select-pane -t 0
tmux send-keys "$EDITOR $HOME/playground/$uuid.js" Enter

tmux select-pane -t 1
tmux send-keys "cd $HOME/playground && ls | entr -cs 'node $HOME/playground/$uuid.js'" Enter

tmux select-pane -t 0
