#!/bin/sh
curl -s "http://sesat.fdi.ucm.es:8080/servicios/rest/sinonimos/json/$1" | jq --arg word "$1" -r '.sinonimos | length as $amount | map(.sinonimo) | "\u001b[32mSinonimos de \($word) (\($amount)): " + join(", ")'
curl -s "http://sesat.fdi.ucm.es:8080/servicios/rest/antonimos/json/$1" | jq --arg word "$1" -r '.antonimos | length as $amount | map(.antonimo) | "\u001b[31mAntonimos de \($word) (\($amount)): " + join(", ")+ "\u001b[0m"'

