#!/bin/bash
set -e
test -z "$1" && echo "I need a file to transfer" && exit 1
test ! -e "$1" && echo "$1 it is not a valid file" && exit 1

url="$(curl -s --upload-file "$1" https://transfer.sh | sed -e 's/\.sh/\.sh\/get/')"
echo "$url"
